import LoginPage from "./LoginPage"
import SignUp from "./SignUp"
import HomePage from "./HomePage"
import PropertiesPage from "./PropertiesPage"
import PropertyDetailsPage from "./PropertyDetailsPage"
import BookingPage from "./BookingPage"
import ProfilePage from "./ProfilePage"
import Contact from "./Contact"
import About from "./About"
import Dashboard from "./Dashboard"
import PropertyRegistration from "./PropertyRegistration"
export { LoginPage, SignUp, HomePage, PropertiesPage, PropertyDetailsPage, BookingPage, ProfilePage, Contact, About, Dashboard, PropertyRegistration }